baseurl: https://teacup2021.github.io/
publishDir: "../teacup2021.github.io"
languageCode: en-us
title: Peijun Sang
theme: hugo-astatine-theme
preserveTaxonomyNames: yes
rssLimit: 10
paginate: 10
pygmentsCodefences: yes
pygmentsStyle: native
taxonomies:
  category: categories
  tag: tags
permalinks:
  page: /:slug/
  post: /:slug/
menu:
  main:
    # - name: Posts
    #   url: /post/
    #   weight: -150
    - name: Publication
      url: /pub/
      weight: -120
    - name: Group
      url: /group/
      weight: -110 
    - name: Contact
      url: /contact/
      weight: -100
    # - name: Tags
    #   url: /tags/
    #   weight: -120
    # - name: Categories
    #   url: /categories/
    #   weight: -130
params:
  authorName: Peijun Sang
  description: Hello world
  imgname:
    alt: Profile picture
    blogrss: yes
    name: img/main.jpg
sitemap:
  filename: sitemap.xml
